# Generated by Django 3.2.18 on 2023-04-26 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dlclpbfkf/image/upload/v1680812148/user-icon_rdjd49.png', max_length=255, verbose_name='image'),
        ),
    ]
