# Generated by Django 3.2.18 on 2023-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20230503_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pic/anime.jpg', upload_to='profile_pics'),
        ),
    ]
