# Generated by Django 3.2.18 on 2023-04-27 19:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_auto_20230423_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dlclpbfkf/image/upload/v1680545745/food-placeholder_j41avo.png', max_length=255, verbose_name='image'),
        ),
    ]
